version: '3'
services:

  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: 'Datapipeline_DB'
      POSTGRES_USER: 'Datapipeline_DB_user'
      POSTGRES_PASSWORD: 'Datapipeline_DB_pwd'
      host : '0.0.0.0'


networks:
  default:
    external:
      name: 'myNetwork_Datapipeline'
